### ISSUE TITLE
`window` is not defined when using with webpack

### ISSUE THREAD

**Issue by woitechen** [GoogleChromeLabs/clooney#128]
Hello! I'm trying to use clooney with webpack + lit-html, but I'm keep getting errors.

![image](https://user-images.githubusercontent.com/37726261/46204696-8987fe80-c2f4-11e8-8a38-2de6147ad324.png)

It appears that clooney is executing lit-html stuff in a web worker, even if lit-html is not being used in the class spawned by clooney. My `tsconfig.json` are targeting es2017, so that's not the problem.

Here is my webpack config (using webpack-serve): [webpack.dev.js](https://gist.github.com/woitechen/ac95ec10429ff3dfe1e55e5701ec433b).
And the file where clooney is being used: [video_card.view.ts](https://gist.github.com/woitechen/a5d396171aa126f46d33f318d4db0596).
All the code to reproduce the issue is available at my repo: [youtube-collection](https://github.com/woitechen/youtube-collection).

Clone the repo and run `yarn && yarn serve`.
Thanks for your amazing work.

**Comment by adammedford** [comment]
At a glance this looks related to: https://github.com/GoogleChromeLabs/comlink/issues/123

**Comment by woitechen** [comment]
@adammedford, unfortunately, that's not a Typescript compilation issue, since I already tested the same code in plain Javascript and got the same results.

**Comment by adammedford** [comment]
@woitechen yeah sorry I had just seen both issues and assumed they were related. 

Webpack generally struggles with dealing with webworkers so that's the angle I've attacked it from. I was getting the same errors you linked until I started treating the Clooney source as a regular web worker script. I followed instructions for running a webworker from the Angular CLI (uses webpack internally) and it worked. I haven't had time to debug and dig through all the relevant source code to determine why but my first guess is that either Clooney or Commlink are prematurely trying to spawn workers before they've been added to the Window. 

I know this isn't a solution but was hoping I could nudge you in the right direction. If you want more details on my specific implementation I'd be happy to share them but I assume mine are very specific to Angular. 

```
const path = require('path');

const config = {
  entry: './libs/web-worker/src/lib/worker.js',
  mode: 'production',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'worker.js'
  }
};

module.exports = config;
```

**Comment by woitechen** [comment]
@adammedford, thanks for your response! I appreciate if you can share your implementation even that it's Angular specific. All help is welcome!

**Comment by woitechen** [comment]
Finally found a solution. The problem was that as webpack bundles all code into a single file, e.g. `main.js`, and clooney uses `document.currentScript` as the `Worker` source url, the whole application Javascript code was being spawned as a worker, causing a lot of problems. Digging around I found a loader for webpack, [comlink-loader](https://github.com/GoogleChromeLabs/comlink-loader), that fit my needs.

**Comment by adammedford** [comment]
@woitechen I apologize for not getting you examples in time but I appreciate you following up with the solution you found. I think that will be even cleaner than my approach so I'm definitely going to steal it. Thanks.

**Comment by rosslavery** [comment]
@adammedford Would you be able to share your solution to make clooney play nicely with Angular CLI? Followed the official docs, but no go. Same error as this issue.
